export const TOGGLE_DROPMENU_NAVBAR = "TOGGLE_DROPMENU_NAVBAR"
export const TOGGLE_AUTH_FORM_NAVBAR = "TOGGLE_AUTH_FORM_NAVBAR"
export const RESET_NAVBAR = "RESET_NAVBAR"
export const TOGGLE_POPUP_WARNING_NAVBAR = "TOGGLE_POPUP_WARNING_NAVBAR"
